apiVersion: apis.kcp.dev/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: today.kafkainstances.rhosak.kcp.github.com
spec:
  group: rhosak.kcp.github.com
  names:
    kind: KafkaInstance
    listKind: KafkaInstanceList
    plural: kafkainstances
    singular: kafkainstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.region
      name: Region
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.bootstrapServerHost
      name: BootstrapServerHost
      type: string
    name: v1
    schema:
      description: KafkaInstance is the Schema for the kafkainstances API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KafkaInstanceSpec defines the desired state of KafkaInstance
          properties:
            cloudProvider:
              description: Foo is an example field of KafkaInstance. Edit kafkainstance_types.go
                to remove/update
              type: string
            multiAz:
              type: boolean
            name:
              type: string
            reauthenticationEnabled:
              type: boolean
            region:
              type: string
          type: object
        status:
          description: KafkaInstanceStatus defines the observed state of KafkaInstance
          properties:
            bootstrapServerHost:
              type: string
            href:
              type: string
            id:
              type: string
            instanceType:
              type: string
            kind:
              type: string
            message:
              type: string
            owner:
              type: string
            phase:
              type: string
            region:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              format: date-time
              type: string
            updatedAt:
              format: date-time
              type: string
            version:
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}

---
